### ISSUE TITLE
Freezes upon seconds

### ISSUE THREAD

**Issue by manu4gmz** [zappar-xr/zappar-threejs-instant-tracking-standalone-bootstrap#1]
I'm very thrilled about this zappar update, firstly because I love Three Js and I had to work with ZapWorks which wasn't that great. 

I tried to get the webpack version started first but I didn't have luck. The standalone version on the other hand was really easy to pull of. I got it working through an Express server and Ngrok to get the HTTPS protocol.

When I entered with the browser with my phone I gave it permissions to use the camera, I worked for a couple of seconds, but then it froze. This keeps happening upon reloading the page.

I'm only using the cube example and it doesn't get re-rendered, even the background is frozen and the cube is well positioned.

I'm using Chrome Browser in with Android 9.

Any advice would be great, I'm going to keep trying with the other version!
Thanks

**Comment by cgauld** [comment]
Hi! I think this is likely to be a licensing issue - basically the library checks where it's being hosted to make sure there's a license. However if you test locally (using 127.0.0.1) or on your local network (192.168.* for example), or by uploading to ZapWorks, then the check passes OK. Would it be possible to try running on your local network? To make this easier we've provided a command line utility here: https://www.npmjs.com/package/@zappar/zapworks-cli
Try installing that then running the following in the folder with your index.html etc:
```
zapworks serve --lan
```
Then visiting https://<your-local-network-ip>:8080 from your phone
Hopefully that should work :-)
NGROK is a really useful tool though (we use it at Zappar too :-) ) so I think it makes sense for us to make an exception for it for licensing. I'll discuss that with the team.

Let me know if that answers your question :-)

**Comment by cgauld** [comment]
Hi @manu4gmz I've got a wee update for you!

We've updated the library handle this more gracefully, removing the freeze, and we've also whitelisted ngrok so you can use *.ngrok.io domains without having to worry about licensing. Update to version 0.2.3 of zappar-threejs to get the latest version :-)

We've also updated the library's readme to make things more clear - check out the 'Hosting and Publishing' section over here: [https://www.npmjs.com/package/@zappar/zappar-threejs](https://www.npmjs.com/package/@zappar/zappar-threejs).

Let me know if that sorts things out! I'm going to close this issue for the time being but feel free to comment here if you have any other questions
